apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yvwmcbz9b-go 
  janus-idp.io/tekton: yvwmcbz9b-go
  backstage.io/kubernetes-id: yvwmcbz9b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yvwmcbz9b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml